[[runners]]
  executor = "custom"
  [runners.custom]
    config_exec = "gitlab-vagrant-driver"
    config_args = [ "config", "image=bento/windows-11", "provider=virtualbox", "template=/opt/homebrew/share/gitlab-vagrant-driver/Vagrantfile.vbox.win.erb" ]

    prepare_exec = "gitlab-vagrant-driver"
    prepare_args = [ "prepare" ]

    run_exec = "gitlab-vagrant-driver"
    run_args = [ "run" ]

    cleanup_exec = "gitlab-vagrant-driver"
    cleanup_args = [ "cleanup" ]
